projet-Photographe/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use FOS\UserBundle\Model\User as BaseUser;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="datetime", nullable=true, options={"default" : "CURRENT_TIMESTAMP"})
     */
    protected $Date_inscription;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Adress", mappedBy="User", orphanRemoval=true))
     */
    private $adresses;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LivreDOr", mappedBy="User")
     */
    protected $livreDOrs;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Galery", inversedBy="users")
     */
    protected $Galery;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commande", mappedBy="User")
     */
    protected $commandes;

    public function __construct()
    {
        parent::__construct();
        $this->adresses = new ArrayCollection();
        $this->livreDOrs = new ArrayCollection();
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }





    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->Date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $Date_inscription): self
    {
        $this->Date_inscription = $Date_inscription;

        return $this;
    }

    /**
     * @return Collection|Adress[]
     */
    public function getAdresses(): Collection
    {
        return $this->adresses;
    }

    public function addAdress(Adress $adress): self
    {
        if (!$this->adresses->contains($adress)) {
            $this->adresses[] = $adress;
            $adress->setUser($this);
        }

        return $this;
    }

    public function removeAdress(Adress $adress): self
    {
        if ($this->adresses->contains($adress)) {
            $this->adresses->removeElement($adress);
            // set the owning side to null (unless already changed)
            if ($adress->getUser() === $this) {
                $adress->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|LivreDOr[]
     */
    public function getLivreDOrs(): Collection
    {
        return $this->livreDOrs;
    }

    public function addLivreDOr(LivreDOr $livreDOr): self
    {
        if (!$this->livreDOrs->contains($livreDOr)) {
            $this->livreDOrs[] = $livreDOr;
            $livreDOr->setUser($this);
        }

        return $this;
    }

    public function removeLivreDOr(LivreDOr $livreDOr): self
    {
        if ($this->livreDOrs->contains($livreDOr)) {
            $this->livreDOrs->removeElement($livreDOr);
            // set the owning side to null (unless already changed)
            if ($livreDOr->getUser() === $this) {
                $livreDOr->setUser(null);
            }
        }

        return $this;
    }

    public function getGalery(): ?Galery
    {
        return $this->Galery;
    }

    public function setGalery(?Galery $Galery): self
    {
        $this->Galery = $Galery;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */


}

projet-Photographe/src/Controller/HeaderController.php
<?php

namespace App\Controller;

use App\Repository\GaleryRepository;
use App\Repository\SitePhotoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HeaderController extends AbstractController
{
    /**
     * @Route("/header", name="header")
     */
    public function index(GaleryRepository $galeryRepository, SitePhotoRepository $sitePhotoRepository )
    {
        $galeries = $galeryRepository->findAll();
        $sitePhoto = $sitePhotoRepository->findAll();


        return $this->render('header/index.html.twig', [
            'galeries' => $galeries,
            'sitePhoto' => $sitePhoto
        ]);
    }
}

projet-Photographe/templates/header/index.html.twig
{% dump %}

<div class="background-white" id="header-white">
        <div class="row">
            <div class="col-xl-12  m-auto center-elem">
                <div class="row">
                    <div class=" col-xl-2 col-md-2 col-sm-12  m-auto center-elem">
                        <a href="{{ path('accueil') }}">
                            <img class="logo-header"  src="/asset/img/logo/Logo-BM.png">
                        </a>
                    </div>
                    <div class="d-none d-xl-block col-xl-2  m-auto center-elem">
                        <img class="signature" src="/asset/img/logo/watermark.png">
                    </div>
                    <div class="d-block d-lg-none col-md-6 col-sm-12  m-auto center-elem">
                        <img class="burger" src="/asset/img/Logo_burger.png">
                    </div>

                    <div class="d-none d-lg-block col-xl-6 col-md-6 col-sm-6 row menu-white  m-auto center-elem">
                                <a href="#" class="col-sm-3 a-header-white">{{ 'menu.home.particulier' | trans }}</a>
                                <a href="#" class="col-sm-3 a-header-white">{{ 'menu.home.professionnel' | trans }}</a>

                                <a href="#" class="col-sm-3 a-header-white">{{ 'menu.home.galery' | trans }}</a>
                                <a href="#" class="col-sm-3 a-header-white">{{ 'menu.home.contact' | trans }}</a>
                    </div>
                    <div class="m-auto center-elem">
                        {% if is_granted('ROLE_USER') %}
                            {{ render(controller('App\\Controller\\LoggedInController::index')) }}
                        {% else %}
                            <div class="col-xl-2 col-md-2 col-sm-12 ">
                                <div class="adherent">
                                    <form action="{{ path("fos_user_security_check") }}" method="post">
                                        <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}" />
                                        <input  class="input" type="text" id="username" name="_username" required="required" autocomplete="username" placeholder="Identifiant"/><br>
                                        <input  class="input" type="password" id="password" name="_password" required="required" autocomplete="current-password" placeholder="Mot de passe"/><br>
                                        <div>
                                            <input  class="login button-header" type="submit" id="_submit" name="_submit" value="{{ 'security.login.submit'|trans({}, 'FOSUserBundle') }}" />
                                        </div>

                                    </form>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
</div>

<div class="background-black" id="header-black">
    <div class="row">
        <div class="col-xl-12  m-auto center-elem">
            <div class="row">
                <div class=" col-xl-2 col-md-2 col-sm-12  m-auto center-elem">
                    <a href="{{ path('accueil') }}">
                        <img class="logo-header"  src="/asset/img/logo/Logo-BM.png">
                    </a>
                </div>

                <div class="m-auto center-elem">
                    {% if is_granted('ROLE_USER') %}
                        {{ render(controller('App\\Controller\\LoggedInController::index')) }}
                    {% else %}
                        <div class="col-xl-2 col-md-2 col-sm-12 ">
                            <div class="adherent">
                                <form action="{{ path("fos_user_security_check") }}" method="post">
                                    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}" />
                                    <input  class="input" type="text" id="username" name="_username" required="required" autocomplete="username" placeholder="Identifiant"/><br>
                                    <input  class="input" type="password" id="password" name="_password" required="required" autocomplete="current-password" placeholder="Mot de passe"/><br>
                                    <div>
                                        <input  class="login button-header" type="submit" id="_submit" name="_submit" value="{{ 'security.login.submit'|trans({}, 'FOSUserBundle') }}" />
                                    </div>

                                </form>
                            </div>
                        </div>
                    {% endif %}
                </div>
                <div class="col-sm-12 ">
                    <a class="align-right" href="register" style="text-decoration: none; color: white">{{ 'base.header.lien.signIn' | trans }}</a>
                </div>

            </div>
            <div class="row menu-black">
                <a href="#" class="col-sm-3 a-header-black ">{{ 'menu.home.particulier' | trans }}</a>
                <a href="#" class="col-sm-3 a-header-black">{{ 'menu.home.professionnel' | trans }}</a>

                <a href="#" class="col-sm-3 a-header-black">{{ 'menu.home.galery' | trans }}</a>
                <a href="#" class="col-sm-3 a-header-black">{{ 'menu.home.contact' | trans }}</a>
            </div>
            <div class="d-none d-sm-block">
                <div class="row menu-black">
                    <div class="submenu border col-sm-3 p-0 m-0">
                        {% for elem in sitePhoto %}
                            {% if elem.hook in [11, 12, 13, 14, 15, 16,17,18,19,20] %}
                                <a href="{{ path('particuliers_presentation', {'id' : elem.hook}) }} " class="col-sm-3 a-header-black"> {{ elem.Titre }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class=" submenu border col-sm-3 p-0 m-0">
                        {% for elem in sitePhoto %}
                            {% if elem.hook in [1,2,3,4,5,6,7,8,9,10] %}
                                <a href="{{ path('professionels_presentation', {'id' : elem.hook}) }} " class="col-sm-3 a-header-black"> {{ elem.Titre}}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="submenu border col-sm-3 p-0 m-0" >
                        {%  for elem in galeries %}
                            {%  if elem.Statut == 0 %}
                                <a href="{{ path('galerie_image', { 'id': elem.id}) }}" class="col-sm-3 a-header-black">{{ elem.Name }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="submenu border col-sm-3 p-0 m-0">
                        <a href="{{ path('contact') }}" class="col-sm-3 a-header-black">Contact</a>
                        <a href="{{ path('livre_or') }}" class="col-sm-3 a-header-black">Livre d'Or</a>
                    </div>
                </div>
            </div>

        </div>
    </div>

    /*---------------------------------------------*/

    <div class="row">
        <div class="menu offset-1 col-lg-9">


        </div>
    </div>

</div>






{#<div class="background-black" id="header-black">#}
    {#<div class="container">#}
        {#<div class="row ">#}
            {#<div class="col-xl-12 connexion">#}
                {#<div class="row">#}
                    {#<a href="{{ path('accueil') }}">#}
                        {#<img class="col-xl-2 col-md-2 logo-header" src="/asset/img/logo/Logo-BM.png">#}
                    {#</a>#}
                    {#<div class="d-block d-md-none col-md-2">LogoMenu</div>#}

                    {#<div class="d-none d-md-block col-lg-8 col-md-7 col-sm-6 align-header-black">#}
                        {#<div class=" menu-black menu">#}

                                {#<a href="#" class="col-sm-3 a-header-black ">{{ 'menu.home.particulier' | trans }}</a>#}
                                {#<a href="#" class="col-sm-3 a-header-black">{{ 'menu.home.professionnel' | trans }}</a>#}
                                {#<a href="#" class="col-sm-3 a-header-black">{{ 'menu.home.galery' | trans }}</a>#}
                                {#<a href="#" class="col-sm-3 a-header-black">{{ 'menu.home.contact' | trans }}</a>#}

                        {#</div>#}
                    {#</div>#}

                    {#<div class="connexion">#}
                        {#{% if is_granted('ROLE_USER') %}#}
                            {#{{ render(controller('App\\Controller\\LoggedInController::index')) }}#}
                        {#{% else %}#}
                            {#<div class="col-xl-2 col-md-2">#}
                                {#<div class="adherent">#}
                                    {#<form action="{{ path("fos_user_security_check") }}" method="post">#}
                                        {#<input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}" />#}
                                        {#<input  class="input" type="text" id="username" name="_username" required="required" autocomplete="username" placeholder="Identifiant"/><br>#}
                                        {#<input  class="input" type="password" id="password" name="_password" required="required" autocomplete="current-password" placeholder="Mot de passe"/><br>#}
                                        {#<input  class="login button-header" type="submit" id="_submit" name="_submit" value="{{ 'security.login.submit'|trans({}, 'FOSUserBundle') }}" />#}

                                    {#</form>#}
                                {#</div>#}
                            {#</div>#}
                        {#{% endif %}#}
                    {#</div>#}
                    {#<div class="col-lg-12 align-right">#}
                        {#<a class="align-right" href="register" style="text-decoration: none; color: white">{{ 'base.header.lien.signIn' | trans }}</a>#}
                    {#</div>#}
                {#</div>#}
                {#<div class="row">#}
                    {#<div class="menu offset-1 col-lg-9">#}
                                {#<div class="submenu border col-sm-3 p-0 m-0">#}
                                    {#{% for elem in sitePhoto %}#}
                                        {#{% if elem.hook in [11, 12, 13, 14, 15, 16,17,18,19,20] %}#}
                                    {#<a href="{{ path('particuliers_presentation', {'id' : elem.hook}) }} " class="col-sm-3 a-header-black"> {{ elem.Titre }}</a>#}
                                        {#{% endif %}#}
                                    {#{% endfor %}#}
                                   {#</div>#}
                                {#<div class=" submenu border col-sm-3 p-0 m-0">#}
                                    {#{% for elem in sitePhoto %}#}
                                        {#{% if elem.hook in [1,2,3,4,5,6,7,8,9,10] %}#}
                                            {#<a href="{{ path('professionels_presentation', {'id' : elem.hook}) }} " class="col-sm-3 a-header-black"> {{ elem.Titre}}</a>#}
                                        {#{% endif %}#}
                                    {#{% endfor %}#}
                                       {#</div>#}
                                {#<div class="submenu border col-sm-3 p-0 m-0" >#}
                                    {#{%  for elem in galeries %}#}
                                        {#{%  if elem.Statut == 0 %}#}
                                    {#<a href="{{ path('galerie_image', { 'id': elem.id}) }}" class="col-sm-3 a-header-black">{{ elem.Name }}</a>#}
                                        {#{% endif %}#}
                                    {#{% endfor %}#}
                                {#</div>#}
                                {#<div class="submenu border col-sm-3 p-0 m-0">#}
                                    {#<a href="{{ path('contact') }}" class="col-sm-3 a-header-black">Contact</a>#}
                                    {#<a href="{{ path('livre_or') }}" class="col-sm-3 a-header-black">Livre d'Or</a>#}
                                {#</div>#}
                    {#</div>#}

                {#</div>#}

                {#</div>#}
            {#</div>#}
        {#</div>#}
    {#</div>#}
{#</div>#}